title: Manu Arora
email: manuarorawork@gmail.com
description: My thoughts on Technology and the ever changing Web Development world
author: Manu Arora
baseurl: ""
url: "http://www.manuarora.me/"

# Social Profiles
twitter_username: mannupaaji
github_username: manuarora700
instagram_username: mannupaaji
linkedin_username: manuarora28

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-159925752-1 # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
